# テーマ、https://github.com/alacritty/alacritty-theme
import = [
    "~/.config/alacritty/themes/themes/carbonfox.toml"
]


[window]
padding = { x = 2, y = 2 }
dynamic_padding = true
blur = true
opacity = 0.8
option_as_alt = "Both"


[env]
term = "xterm-256color"


[font]
size = 12.0
offset = { x = 0, y = 8 }
glyph_offset = { x = 0, y = 4 }

[font.normal]
family = "HackGen35 Console NF"
style = "Regular"

[font.bold]
family = "HackGen35 Console NF"
style = "Bold"